export const productDataList = [
  {
    productName: "beatXP Marv Neo 1.85'' HD Display with Bluetooth Calling Smartwatch",
    price: {
      mrp: 6999,
      cost: 4049,
      discountPercent: 42,
    },
    subcategory: 'Smart Watches',
    productImage: 'https://rukminim2.flixcart.com/image/416/416/xif0q/smartwatch/a/0/j/4-6-bxio2003-android-ios-beatxp-yes-original-imagt9fsjarfyhfm.jpeg?q=70',
    category: 'Electronics',
    description: "High-performance and robust, the beatXP Marv Neo Smartwatch is an excellent addition to your watch collection. It lends high clarity on its up to 4.699 cm (1.85) wide TFT HD display. Additionally, its stylish screen with personalised watch faces offers an appealing appearance. Also, this smartwatch's EzyPair technology ensures a stable connection for hassle-free Bluetooth calling. Moreover, this smartwatch allows you to track your health indicators, such as calorie intake and more while participating in various fitness and sports activities.",
    tagline: 'Best Seller',
    quantity: 1,
    seller: "652ebf61b409f906d81645a3",
  },
  {
    productName: 'NOVA NHP 8106 Hair Dryer  (1400 W, Black)',
    price: {
      mrp: 1899,
      cost: 1124,
      discountPercent: 40,
    },
    subcategory: 'Trimmers, Dryers & more',
    productImage: 'https://rukminim2.flixcart.com/image/416/416/khtghow0pkrrdj-0/hair-dryer/p/o/0/nhp-8106-nova-original-imafxtddk7rdercf.jpeg?q=70',
    category: 'Personal Care Appliances',
    description: 'The Nova Professional NHP 8220 Hair Dryer is a powerful and efficient hair styling tool. It operates at 1800 W, making it quick and effective in drying and styling your hair. The multicolor design adds a touch of style to your grooming routine. This hair dryer is perfect for both personal and professional use, offering salon-like results from the comfort of your home. Style your hair effortlessly with Nova Professional NHP 8220 Hair Dryer.',
    tagline: 'Kubra, Nova & more',
    quantity: 1,
    seller: "652ebf61b409f906d81645a3",
  },
  {
    productName: 'Longway Speedy 300 mm Energy Saving 3 Blade Table Fan  (Black, Pack of 1)',
    price: {
      mrp: 2250,
      cost: 1199,
      discountPercent: 46,
    },
    subcategory: 'Table Fans',
    productImage: 'https://rukminim2.flixcart.com/image/416/416/xif0q/fan/s/i/r/speedy-230-1-table-fan-300-longway-original-imagpgp5kzufdcxj.jpeg?q=70',
    category: 'Home & Kitchen',
    description: 'Table Fan. Perfect size fan for use on a table, desk or in an RV. Whisper quiet, powerful airflow and reliable operation in a compact 6" size. Two adjustable speeds to customize airflow: high or low settings. Tough break-resistant ABS plastic blades. ',
    tagline: 'Top Selling',
    quantity: 1,
    seller: "652ebf61b409f906d81645a3",
  },
  {
    productName: 'boAt Rockerz 255 Pro+ /258 Pro+ with ASAP Charge and upto 60 Hours Playback Bluetooth Headset  (Active Black, In the Ear)',
    price: {
      mrp: 2990,
      cost: 1199,
      discountPercent: 59,
    },
    subcategory: 'Headphones',
    productImage: 'https://rukminim2.flixcart.com/image/416/416/l31x2fk0/headphone/a/s/h/-original-image9ehehz8amg2.jpeg?q=70',
    category: 'Electronics',
    description: 'boAt Rockerz 255 Pro+ is a power-packed in-ear wireless neckband headphone that has been ergonomically designed to meet the needs of music lovers. The headphones come equipped with Bluetooth V5.0 for instant wireless connectivity. Its super powerful 300mAh battery provides a humongous playtime of up to 60 hours for an extended audio bliss. Its 10mm dynamic drivers help supply superior musical experience to the user with immersive sound. With our ASAP fast charge technology, you can get the headphones fully charged in just 60 minutes. It also offers resistance against water and sweat with IPX7 rated premium build. One can control the playback and calls easily via the provided multifunction controls and even summon respective smart Voice Assistant. Get ready to get enthralled by the pumped up audio and soaring vibe of Rockerz 255 Pro+',
    tagline: 'Grab Now!',
    quantity: 1,
    seller: "652ebf61b409f906d81645a3",
  },
  {
    productName: "SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)  (4 GB RAM)",
    price: {
      mrp: 14999,
      cost: 9199,
      discountPercent: 38,
    },
    subcategory: 'Mobile Phones',
    productImage: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/x/x/s/-original-imagfhu6dcpdnqkh.jpeg?q=70",
    category: 'Electronics',
    description: 'This smartphone features a terrific 16.62 cm (6.6) FHD+ LCD Display that can effortlessly blow your mind with its incredible performance. Furthermore, this phone boasts a 50 MP Triple Camera setup that allows you to capture awesomeness with a gentle tap. Moreover, the Samsung Galaxy F13 sports up to 8 GB of RAM and features an innovative RAM plus technology that taps into the phone’s internal storage to elevate its performance.',
    tagline: 'New Arrival',
    quantity: 1,
    seller: "652ebf61b409f906d81645a3",
  },
  {
    productName: "APPLE iPhone 13 (Midnight, 128 GB)",
    price: {
      mrp: 19999,
      cost: 14199,
      discountPercent: 30,
    },
    subcategory: 'Mobile Phones',
    productImage: "https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/s/l/c/iphone-13-mlpf3hn-a-apple-original-imag6vzz5qvejz8z.jpeg?q=70",
    category: 'Electronics',
    description: 'iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.',
    tagline: 'New Arrival',
    quantity: 1,
    seller: "652ebf61b409f906d81645a3",
  },
];

export const bannerData = [
  { _id: 1, url: 'https://static.vecteezy.com/system/resources/previews/011/871/820/non_2x/online-shopping-on-phone-buy-sell-business-digital-web-banner-application-money-advertising-payment-ecommerce-illustration-search-vector.jpg' },
  { _id: 2, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/a5320d3f852657e8.jpg?q=50' },
  { _id: 3, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/5df65ad101e18dbf.jpg?q=50' },
  { _id: 4, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/8a89ee09acc1a9e5.jpg?q=50' },
  { _id: 5, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/ed12b7707a04473c.jpg?q=50' },
]